/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const init_game: (a: number, b: number, c: number) => void;
export const tick: (a: number, b: number) => void;
export const get_unit_position: (a: number) => any;
export const get_resources: (a: number) => number;
export const get_state_checksum: () => [number, number];
export const get_render_data: (a: number) => [number, number];
export const issue_command: (a: number, b: number) => void;
export const get_fog_data: (a: number) => [number, number];
export const get_terrain_data: () => [number, number];
export const get_map_size: () => number;
export const get_game_state: () => [number, number];
export const get_game_result: () => [number, number];
export const get_unit_count_for_player: (a: number) => number;
export const get_units_by_type: (a: number, b: number, c: number) => [number, number];
export const get_unit_health: (a: number) => [number, number];
export const get_unit_state: (a: number) => [number, number];
export const get_unit_carrying: (a: number) => number;
export const get_building_count_for_player: (a: number) => number;
export const get_buildings_by_type: (a: number, b: number, c: number) => [number, number];
export const get_production_queue: (a: number) => [number, number];
export const get_resource_nodes: () => [number, number];
export const is_tile_visible: (a: number, b: number, c: number) => number;
export const get_visible_tile_count: (a: number) => number;
export const get_tile_type: (a: number, b: number) => [number, number];
export const is_pathable: (a: number, b: number) => number;
export const fast_forward: (a: number) => void;
export const get_tick_count: () => number;
export const get_building_progress: (a: number) => number;
export const get_unit_count: () => number;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
