import { chromium } from "@playwright/test";
const U = "https://rfp-finder-ph.fly.dev";
const b = await chromium.launch();
const d = await b.newPage({ viewport: { width: 1280, height: 800 } });
await d.goto(U, { waitUntil: "networkidle" });
const box = d.getByTestId("chat-input");
await box.click();
await box.fill("small drainage jobs in Cavite under 5M, PCAB C");
await d.waitForTimeout(300);
await box.press("Enter");
await d.locator('[data-testid="assistant-text"] strong, [data-testid="assistant-text"] li, [data-testid="cards"]').first().waitFor({ timeout: 110000 });
const hasMd = await d.locator('[data-testid="assistant-text"] strong, [data-testid="assistant-text"] li').count();
const hasCards = await d.getByTestId("cards").count();
await d.screenshot({ path: "qa/shots/live-desktop.png", fullPage: true });
console.log("desktop markdown elements:", hasMd, "cards blocks:", hasCards);
const m = await b.newPage({ viewport: { width: 390, height: 844 } });
await m.goto(U, { waitUntil: "networkidle" });
await m.screenshot({ path: "qa/shots/live-mobile.png", fullPage: true });
console.log("mobile overflow:", await m.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth));
await b.close();
