/**
 * Command card — shows available actions for selected entities.
 * Buildings: train buttons + production progress.
 * Units: attack-move, stop buttons.
 */

import { RenderUnit, getProductionQueue, getBuildingProgress } from '../wasm/bridge.js';
import { ClientState } from '../game/state.js';
import { GameCommand, createTrainCommand, createAttackMoveCommand, createStopCommand } from '../game/commands.js';

export class CommandCard {
  private el: HTMLElement;
  private pendingCommands: GameCommand[] = [];

  constructor() {
    this.el = document.getElementById('command-card')!;
  }

  update(state: ClientState, renderData: RenderUnit[]): void {
    const ids = state.selectedEntityIds;
    if (ids.length === 0) {
      this.el.innerHTML = '<span style="color:#666">No selection</span>';
      return;
    }

    // Find the first selected entity in render data
    const entity = renderData.find((u) => ids.includes(u.id));
    if (!entity) {
      this.el.innerHTML = '<span style="color:#666">Entity not visible</span>';
      return;
    }

    let html = '';

    if (entity.s >= 100) {
      // Building — show production queue and train buttons
      const progress = getBuildingProgress(entity.id);
      const queue = getProductionQueue(entity.id);

      html += `<div style="margin-bottom:4px;color:#aaa">Building #${entity.id}</div>`;

      if (progress < 1.0) {
        const pct = Math.round(progress * 100);
        html += `<div style="margin-bottom:4px">Construction: ${pct}%</div>`;
      } else {
        // Train buttons
        html += `<div style="margin-bottom:4px">`;
        html += `<button class="cmd-btn" data-cmd="train-worker" style="margin:2px;padding:4px 8px;cursor:pointer;font-size:11px">Train Worker</button>`;
        html += `<button class="cmd-btn" data-cmd="train-rifleman" style="margin:2px;padding:4px 8px;cursor:pointer;font-size:11px">Train Rifleman</button>`;
        html += `</div>`;

        // Production queue
        if (queue.length > 0) {
          html += `<div style="color:#aaa;font-size:11px">Queue:</div>`;
          for (const item of queue) {
            const pct = Math.round(item.progress * 100);
            html += `<div style="font-size:11px">${item.unitType} (${pct}%)</div>`;
          }
        }
      }
    } else {
      // Unit — show action buttons
      html += `<div style="margin-bottom:4px;color:#aaa">Unit #${entity.id}</div>`;
      html += `<button class="cmd-btn" data-cmd="attack-move" style="margin:2px;padding:4px 8px;cursor:pointer;font-size:11px">Attack Move (A)</button>`;
      html += `<button class="cmd-btn" data-cmd="stop" style="margin:2px;padding:4px 8px;cursor:pointer;font-size:11px">Stop (S)</button>`;
    }

    this.el.innerHTML = html;

    // Attach click handlers
    this.el.querySelectorAll('.cmd-btn').forEach((btn) => {
      btn.addEventListener('click', (e) => {
        const cmd = (e.target as HTMLElement).dataset.cmd;
        this.handleButton(cmd!, state);
      });
    });
  }

  private handleButton(cmd: string, state: ClientState): void {
    const ids = state.selectedEntityIds;
    if (ids.length === 0) return;

    switch (cmd) {
      case 'train-worker':
        this.pendingCommands.push(createTrainCommand(state.playerId, ids, 'Worker'));
        break;
      case 'train-rifleman':
        this.pendingCommands.push(createTrainCommand(state.playerId, ids, 'Rifleman'));
        break;
      case 'attack-move':
        // This would need a target click — for now just mark as pending
        // The input manager handles the actual attack-move flow
        break;
      case 'stop':
        this.pendingCommands.push(createStopCommand(state.playerId, ids));
        break;
    }
  }

  /** Flush any commands generated by button clicks. */
  flushCommands(): GameCommand[] {
    const cmds = this.pendingCommands;
    this.pendingCommands = [];
    return cmds;
  }
}
